#!/usr/bin/env python
#!coding=utf-8
 
import RPi.GPIO as GPIO
from time import sleep
import rospy
import time
from std_msgs.msg import Int32

class shoot():
    def callback(self,data):
        self.send = data.data

    def __init__(self):
        GPIO.setmode(GPIO.BCM)
        self.send = 1  #self.send is not go to area
        rospy.Subscriber("send_1",Int32,self.callback)
        while not rospy.is_shutdown():
            if self.send == 0:
                time.sleep(1)
                GPIO.setup(24,GPIO.OUT)
                print("shoot")
                time.sleep(1)
                GPIO.setup(24,GPIO.IN)
                print("back")
                self.send = 1

if __name__ == '__main__':
    rospy.init_node('shoot')
    shoot()
