#!/usr/bin/env python
#!coding=utf-8
 
import RPi.GPIO as GPIO
from time import sleep
import rospy
import time
from std_msgs.msg import Int32
from geometry_msgs.msg import Twist

class shoot():
    def callback(self,data):
        self.send = data.data

    def __init__(self):
        #GPIO.setmode(GPIO.BCM)
        self.send = 1  #self.send is not go to area
        rospy.Subscriber("send_1",Int32,self.callback)
        self.cmd_vel = rospy.Publisher('cmd_vel', Twist, queue_size=1)#1
        self.move_cmd = Twist()#1
        while not rospy.is_shutdown():
            if self.send == 0:
                #time.sleep(1)
                print("shoot")
                #GPIO.setup(24,GPIO.OUT)
                for i in range(0,55):
                    self.move_cmd.linear.x = 1.00#1
                    self.cmd_vel.publish(self.move_cmd) #1
                    time.sleep(0.1)
                #GPIO.setup(24,GPIO.IN)
                print("back")
                for i in range(0,55):
                    self.move_cmd.linear.x = -1.00#1
                    self.cmd_vel.publish(self.move_cmd) #1
                    time.sleep(0.1)            
                self.send = 1

if __name__ == '__main__':
    rospy.init_node('shoot')
    shoot()
